export {
  applyResendEmailEvent,
  createEmailLogEntry,
  createEmailLogEntryOnce,
  getEmailLogForSession,
  getEmailStatusesForSessions,
  markEmailClicked,
  markEmailFailed,
  markEmailOpened,
  markEmailPollFailed,
  markEmailSending,
  recordResendWebhookEvent,
  updateEmailStatusByResendId,
  type CreateEmailLogResult,
  type EmailLogRow,
  type EmailPurpose,
  type EmailStatus,
  type EmailSummary,
} from '@cap/mailer';
